name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue! One of the maintainers will be here soon.'
        pr-message: 'Thank you for creating your first pull request! Sit tight, one of the maintainers will review this soon.'
